services:
  - type: web
    name: househunt-backend
    env: python
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn househunt.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: househunt.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: househunt-db
          property: connectionString
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET_NAME
        sync: false
      - key: AWS_S3_REGION
        value: eu-north-1
      - key: CLOUDFRONT_DOMAIN
        sync: false
      - key: AT_USERNAME
        sync: false
      - key: AT_API_KEY
        sync: false
      - key: AT_SENDER_ID
        value: HouseHunt

databases:
  - name: househunt-db
    databaseName: househunt
    user: househunt