# Generated by Django 5.0.4 on 2026-03-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_by', models.CharField(max_length=150)),
                ('performed_by_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('ban_landlord', 'Banned Landlord'), ('unban_landlord', 'Unbanned Landlord'), ('delete_house', 'Deleted House'), ('approve_feedback', 'Approved Feedback'), ('reject_feedback', 'Rejected Feedback'), ('delete_tenant', 'Deleted Tenant'), ('delete_feedback', 'Deleted Feedback'), ('other', 'Other')], max_length=50)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_repr', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
