# Generated by Django 4.2.28 on 2026-08-04 01:42

from django.db import migrations, models


def backfill_property_type(apps, schema_editor):
    """
    Before this migration `bedrooms == 0` was the encoding for "Bedsitter".
    Preserve that meaning instead of letting those rows take the
    'apartment' column default.
    """
    House = apps.get_model("houses", "House")
    House.objects.filter(bedrooms=0).update(property_type="bedsitter")


def unbackfill(apps, schema_editor):
    # Nothing to undo — the column is dropped on reverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='property_type',
            field=models.CharField(choices=[('single_room', 'Single Room'), ('bedsitter', 'Bedsitter'), ('studio', 'Studio Apartment'), ('apartment', 'Apartment / Flat'), ('maisonette', 'Maisonette'), ('bungalow', 'Bungalow'), ('townhouse', 'Townhouse'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('servant_quarter', 'Servant Quarter (SQ)')], default='apartment', max_length=32),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedrooms',
            field=models.IntegerField(choices=[(0, 'No separate bedroom'), (1, '1 Bedroom'), (2, '2 Bedrooms'), (3, '3 Bedrooms'), (4, '4 Bedrooms'), (5, '5+ Bedrooms')]),
        ),
        migrations.RunPython(backfill_property_type, unbackfill),
    ]
